import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1752312654137 implements MigrationInterface {
    name = 'InitialSchema1752312654137'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "permissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "description" character varying, CONSTRAINT "UQ_48ce552495d14eae9b187bb6716" UNIQUE ("name"), CONSTRAINT "PK_920331560282b8bd21bb02290df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "description" character varying, CONSTRAINT "UQ_648e3f5447f725579d7d4ffdfb7" UNIQUE ("name"), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."addresses_type_enum" AS ENUM('shipping', 'billing', 'both')`);
        await queryRunner.query(`CREATE TYPE "public"."addresses_status_enum" AS ENUM('active', 'inactive', 'default')`);
        await queryRunner.query(`CREATE TABLE "addresses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid NOT NULL, "type" "public"."addresses_type_enum" NOT NULL DEFAULT 'shipping', "status" "public"."addresses_status_enum" NOT NULL DEFAULT 'active', "firstName" character varying(100) NOT NULL, "lastName" character varying(100) NOT NULL, "company" character varying(100), "addressLine1" character varying(255) NOT NULL, "addressLine2" character varying(255), "city" character varying(100) NOT NULL, "state" character varying(100) NOT NULL, "postalCode" character varying(20) NOT NULL, "country" character varying(100) NOT NULL, "phone" character varying(20), "email" character varying(255), "isDefault" boolean NOT NULL DEFAULT false, "notes" text, CONSTRAINT "PK_745d8f43d3af10ab8247465e450" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "type" character varying NOT NULL, "firstName" character varying NOT NULL, "lastName" character varying NOT NULL, "userName" character varying, "email" character varying NOT NULL, "password" character varying NOT NULL, "phone" character varying, "emailVerified" boolean DEFAULT false, "isActive" boolean DEFAULT false, CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id")); COMMENT ON COLUMN "users"."type" IS 'admin, seller, buyer. Roles outside of the scope has no effect'; COMMENT ON COLUMN "users"."phone" IS 'Phone number'`);
        await queryRunner.query(`CREATE TABLE "media_files" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "scope" character varying NOT NULL DEFAULT 'admin', "uri" character varying, "url" text, "fileName" character varying NOT NULL, "mimetype" character varying NOT NULL, "size" integer NOT NULL, "userId" character varying, CONSTRAINT "UQ_3056d1c65dae9bacd8fa978d266" UNIQUE ("uri"), CONSTRAINT "PK_93b4da6741cd150e76f9ac035d8" PRIMARY KEY ("id")); COMMENT ON COLUMN "media_files"."scope" IS 'Resource scope e.g. admin, seller, buyer'; COMMENT ON COLUMN "media_files"."uri" IS 'File path in S3 bucket for internal files. The URL should be composed on retrieval using a pre-signed URL.'; COMMENT ON COLUMN "media_files"."url" IS 'File URL for public media files (products, blog posts)'`);
        await queryRunner.query(`CREATE TABLE "categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "isParent" boolean DEFAULT false, "parentId" uuid, "name" character varying NOT NULL, "slug" character varying NOT NULL, "description" character varying, "isActive" boolean DEFAULT false, "thumbnailImageId" uuid, "coverImageId" uuid, "isFeatured" boolean DEFAULT false, "isPopular" boolean DEFAULT false, CONSTRAINT "UQ_420d9f679d41281f282f5bc7d09" UNIQUE ("slug"), CONSTRAINT "PK_24dbc6126a28ff948da33e97d3b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9a6f051e66982b5f0318981bca" ON "categories" ("parentId") `);
        await queryRunner.query(`CREATE TABLE "attribute_values" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "variant" character varying, "sku" character varying, "price" numeric, "quantity" integer, "imageId" uuid, "attributeId" uuid, CONSTRAINT "PK_3babf93d1842d73e7ba849c0160" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "attributes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "productId" uuid, CONSTRAINT "UQ_da1145d1b3ffb26e0eacedee627" UNIQUE ("name", "productId"), CONSTRAINT "PK_32216e2e61830211d3a5d7fa72c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "products" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "addedBy" character varying, "userId" character varying, "sellerId" uuid, "name" character varying NOT NULL, "slug" character varying NOT NULL, "thumbnailImgId" uuid, "tags" text, "shortDescription" character varying, "longDescription" character varying, "regularPrice" numeric, "salePrice" numeric, "isVariant" boolean NOT NULL DEFAULT false, "published" boolean NOT NULL DEFAULT false, "approved" boolean NOT NULL DEFAULT false, "stock" integer, "cashOnDelivery" boolean NOT NULL DEFAULT false, "featured" boolean NOT NULL DEFAULT false, "discount" numeric, "discountType" character varying, "discountStartDate" TIMESTAMP, "discountEndDate" TIMESTAMP, "tax" numeric, "taxType" character varying, "shippingType" character varying, "shippingCost" numeric, "estShippingDays" integer, "numOfSales" integer, "metaTitle" character varying, "metaDescription" character varying, "rating" numeric, "externalLink" character varying, "externalLinkBtn" character varying, CONSTRAINT "UQ_464f927ae360106b783ed0b4106" UNIQUE ("slug"), CONSTRAINT "PK_0806c755e0aca124e67c0cf6d7d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."sellers_status_enum" AS ENUM('pending', 'approved', 'rejected', 'suspended', 'inactive')`);
        await queryRunner.query(`CREATE TYPE "public"."sellers_verificationstatus_enum" AS ENUM('unverified', 'pending', 'verified', 'rejected')`);
        await queryRunner.query(`CREATE TABLE "sellers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid NOT NULL, "businessName" character varying, "businessDescription" character varying, "businessPhone" character varying, "businessEmail" character varying, "businessWebsite" character varying, "businessAddress" character varying, "businessCity" character varying, "businessState" character varying, "businessPostalCode" character varying, "businessCountry" character varying, "taxId" character varying, "licenseNumber" character varying, "licenseExpiryDate" TIMESTAMP, "status" "public"."sellers_status_enum" NOT NULL DEFAULT 'pending', "verificationStatus" "public"."sellers_verificationstatus_enum" NOT NULL DEFAULT 'unverified', "verificationDocuments" character varying, "profileImage" character varying, "bannerImage" character varying, "totalProducts" integer NOT NULL DEFAULT '0', "totalSales" integer NOT NULL DEFAULT '0', "totalOrders" integer NOT NULL DEFAULT '0', "totalRevenue" integer NOT NULL DEFAULT '0', "rating" integer NOT NULL DEFAULT '0', "reviewCount" integer NOT NULL DEFAULT '0', "commissionRate" integer, "payoutMethod" character varying, "payoutDetails" character varying, "approvedAt" TIMESTAMP, "approvedBy" character varying, "rejectionReason" character varying, "notes" character varying, CONSTRAINT "UQ_4c1c59db4ac1ed90a1a7c0ff3df" UNIQUE ("userId"), CONSTRAINT "REL_4c1c59db4ac1ed90a1a7c0ff3d" UNIQUE ("userId"), CONSTRAINT "PK_97337ccbf692c58e6c7682de8a2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "shipping_addresses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid, "firstName" character varying NOT NULL, "lastName" character varying NOT NULL, "company" character varying, "addressLine1" character varying NOT NULL, "addressLine2" character varying, "city" character varying NOT NULL, "state" character varying NOT NULL, "postalCode" character varying NOT NULL, "country" character varying NOT NULL, "phone" character varying, "isDefault" boolean NOT NULL DEFAULT false, "isActive" boolean NOT NULL DEFAULT true, "label" character varying, CONSTRAINT "PK_cced78984eddbbe24470f226692" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "order_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "orderId" uuid NOT NULL, "productId" uuid NOT NULL, "productName" character varying NOT NULL, "productSlug" character varying, "quantity" integer NOT NULL, "unitPrice" numeric(10,2) NOT NULL, "totalPrice" numeric(10,2) NOT NULL, "productSnapshot" text, "selectedVariants" text, "sku" character varying, "taxAmount" numeric(10,2) NOT NULL DEFAULT '0', "discountAmount" numeric(10,2) NOT NULL DEFAULT '0', "thumbnailImage" character varying, CONSTRAINT "PK_005269d8574e6fac0493715c308" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."order_status_enum" AS ENUM('pending', 'confirmed', 'processing', 'shipped', 'delivered', 'cancelled', 'refunded', 'returned')`);
        await queryRunner.query(`CREATE TYPE "public"."payment_status_enum" AS ENUM('pending', 'authorized', 'captured', 'failed', 'cancelled', 'refunded', 'partially_refunded')`);
        await queryRunner.query(`CREATE TYPE "public"."payment_method_enum" AS ENUM('credit_card', 'debit_card', 'paypal', 'stripe', 'cash_on_delivery', 'bank_transfer', 'wallet')`);
        await queryRunner.query(`CREATE TABLE "orders" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "orderNumber" character varying NOT NULL, "userId" uuid, "guestId" character varying, "status" "public"."order_status_enum" NOT NULL DEFAULT 'pending', "subtotal" numeric(10,2) NOT NULL, "taxAmount" numeric(10,2) NOT NULL DEFAULT '0', "shippingAmount" numeric(10,2) NOT NULL DEFAULT '0', "discountAmount" numeric(10,2) NOT NULL DEFAULT '0', "totalAmount" numeric(10,2) NOT NULL, "paymentStatus" "public"."payment_status_enum" NOT NULL DEFAULT 'pending', "paymentMethod" "public"."payment_method_enum", "paymentTransactionId" character varying, "paymentGatewayResponse" text, "shippingAddress" text NOT NULL, "billingAddress" text, "shippingMethod" character varying, "trackingNumber" character varying, "estimatedDeliveryDate" TIMESTAMP, "actualDeliveryDate" TIMESTAMP, "notes" text, "adminNotes" text, "couponCode" character varying, "emailSent" boolean NOT NULL DEFAULT false, "cancelledAt" TIMESTAMP, "cancelReason" character varying, "customerEmail" character varying, "customerFirstName" character varying, "customerLastName" character varying, "customerPhone" character varying, CONSTRAINT "UQ_59b0c3b34ea0fa5562342f24143" UNIQUE ("orderNumber"), CONSTRAINT "PK_710e2d4957aa5878dfe94e4ac2f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "order_status_history" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "orderId" uuid NOT NULL, "status" "public"."order_status_enum" NOT NULL, "changedBy" uuid, "notes" text, "notificationSent" boolean NOT NULL DEFAULT false, "previousStatus" "public"."order_status_enum", CONSTRAINT "PK_e6c66d853f155531985fc4f6ec8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."coupon_type_enum" AS ENUM('percentage', 'fixed_amount', 'free_shipping')`);
        await queryRunner.query(`CREATE TABLE "coupons" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "code" character varying NOT NULL, "name" character varying NOT NULL, "description" character varying, "type" "public"."coupon_type_enum" NOT NULL DEFAULT 'percentage', "value" numeric(10,2) NOT NULL, "minimumAmount" numeric(10,2), "maximumDiscount" numeric(10,2), "startDate" TIMESTAMP, "endDate" TIMESTAMP, "usageLimit" integer, "usageCount" integer NOT NULL DEFAULT '0', "usageLimitPerUser" integer, "isActive" boolean NOT NULL DEFAULT true, "createdBy" uuid, "applicableCategories" text, "applicableProducts" text, CONSTRAINT "UQ_e025109230e82925843f2a14c48" UNIQUE ("code"), CONSTRAINT "PK_d7ea8864a0150183770f3e9a8cb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "carts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "guestId" character varying, "userId" character varying, "productId" uuid NOT NULL, "quantity" integer NOT NULL DEFAULT '1', "price" numeric, "variants" text, "isActive" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_b5f695a59f5ebb50af3c8160816" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "role_permissions" ("roleId" uuid NOT NULL, "permissionName" character varying NOT NULL, CONSTRAINT "PK_ac47b71a830e90c75f41040ba1a" PRIMARY KEY ("roleId", "permissionName"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b4599f8b8f548d35850afa2d12" ON "role_permissions" ("roleId") `);
        await queryRunner.query(`CREATE INDEX "IDX_b4f3a5b54478bd9a66cb6ad8e4" ON "role_permissions" ("permissionName") `);
        await queryRunner.query(`CREATE TABLE "user_roles" ("userId" uuid NOT NULL, "roleId" uuid NOT NULL, CONSTRAINT "PK_88481b0c4ed9ada47e9fdd67475" PRIMARY KEY ("userId", "roleId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_472b25323af01488f1f66a06b6" ON "user_roles" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_86033897c009fcca8b6505d6be" ON "user_roles" ("roleId") `);
        await queryRunner.query(`CREATE TABLE "products_photos_media_files" ("productsId" uuid NOT NULL, "mediaFilesId" uuid NOT NULL, CONSTRAINT "PK_7d52b028c70c525fa8d0a61fe69" PRIMARY KEY ("productsId", "mediaFilesId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4df1b7c7386e71711941ac06b4" ON "products_photos_media_files" ("productsId") `);
        await queryRunner.query(`CREATE INDEX "IDX_6a7082c3fa6b04083df2a0107b" ON "products_photos_media_files" ("mediaFilesId") `);
        await queryRunner.query(`CREATE TABLE "products_categories_categories" ("productsId" uuid NOT NULL, "categoriesId" uuid NOT NULL, CONSTRAINT "PK_8fd95511a998d598ff66d500933" PRIMARY KEY ("productsId", "categoriesId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_40e7da0284a5389344605de8da" ON "products_categories_categories" ("productsId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e1d833224b5be535323207473f" ON "products_categories_categories" ("categoriesId") `);
        await queryRunner.query(`ALTER TABLE "addresses" ADD CONSTRAINT "FK_95c93a584de49f0b0e13f753630" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "categories" ADD CONSTRAINT "FK_9a6f051e66982b5f0318981bcaa" FOREIGN KEY ("parentId") REFERENCES "categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "categories" ADD CONSTRAINT "FK_69d45adbc59b8f44730cc411ca1" FOREIGN KEY ("thumbnailImageId") REFERENCES "media_files"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "categories" ADD CONSTRAINT "FK_2c1f40c7ab98d13a79214436d81" FOREIGN KEY ("coverImageId") REFERENCES "media_files"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attribute_values" ADD CONSTRAINT "FK_c81deba612aa9847bae5be6d64c" FOREIGN KEY ("imageId") REFERENCES "media_files"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attribute_values" ADD CONSTRAINT "FK_b8f8e1d9141248b538c9285574e" FOREIGN KEY ("attributeId") REFERENCES "attributes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attributes" ADD CONSTRAINT "FK_2161c27ae1c917301af344493e7" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_e40a1dd2909378f0da1f34f7bd6" FOREIGN KEY ("sellerId") REFERENCES "sellers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_220faed55dfcb27da93f7ac5421" FOREIGN KEY ("thumbnailImgId") REFERENCES "media_files"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sellers" ADD CONSTRAINT "FK_4c1c59db4ac1ed90a1a7c0ff3df" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shipping_addresses" ADD CONSTRAINT "FK_6f522735551c716dc489635b5b7" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_f1d359a55923bb45b057fbdab0d" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_cdb99c05982d5191ac8465ac010" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_151b79a83ba240b0cb31b2302d1" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_status_history" ADD CONSTRAINT "FK_689db3835e5550e68d26ca32676" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_status_history" ADD CONSTRAINT "FK_e8c23988e2e618bbff2b4b43a59" FOREIGN KEY ("changedBy") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coupons" ADD CONSTRAINT "FK_b8e8b137019c03c958da9b62a28" FOREIGN KEY ("createdBy") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "carts" ADD CONSTRAINT "FK_9c77aaa5bc26f66159661ffd808" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_b4599f8b8f548d35850afa2d12c" FOREIGN KEY ("roleId") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_b4f3a5b54478bd9a66cb6ad8e4a" FOREIGN KEY ("permissionName") REFERENCES "permissions"("name") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_472b25323af01488f1f66a06b67" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_86033897c009fcca8b6505d6be2" FOREIGN KEY ("roleId") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products_photos_media_files" ADD CONSTRAINT "FK_4df1b7c7386e71711941ac06b4a" FOREIGN KEY ("productsId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "products_photos_media_files" ADD CONSTRAINT "FK_6a7082c3fa6b04083df2a0107b8" FOREIGN KEY ("mediaFilesId") REFERENCES "media_files"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "products_categories_categories" ADD CONSTRAINT "FK_40e7da0284a5389344605de8dab" FOREIGN KEY ("productsId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "products_categories_categories" ADD CONSTRAINT "FK_e1d833224b5be535323207473f1" FOREIGN KEY ("categoriesId") REFERENCES "categories"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "products_categories_categories" DROP CONSTRAINT "FK_e1d833224b5be535323207473f1"`);
        await queryRunner.query(`ALTER TABLE "products_categories_categories" DROP CONSTRAINT "FK_40e7da0284a5389344605de8dab"`);
        await queryRunner.query(`ALTER TABLE "products_photos_media_files" DROP CONSTRAINT "FK_6a7082c3fa6b04083df2a0107b8"`);
        await queryRunner.query(`ALTER TABLE "products_photos_media_files" DROP CONSTRAINT "FK_4df1b7c7386e71711941ac06b4a"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_86033897c009fcca8b6505d6be2"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_472b25323af01488f1f66a06b67"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_b4f3a5b54478bd9a66cb6ad8e4a"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_b4599f8b8f548d35850afa2d12c"`);
        await queryRunner.query(`ALTER TABLE "carts" DROP CONSTRAINT "FK_9c77aaa5bc26f66159661ffd808"`);
        await queryRunner.query(`ALTER TABLE "coupons" DROP CONSTRAINT "FK_b8e8b137019c03c958da9b62a28"`);
        await queryRunner.query(`ALTER TABLE "order_status_history" DROP CONSTRAINT "FK_e8c23988e2e618bbff2b4b43a59"`);
        await queryRunner.query(`ALTER TABLE "order_status_history" DROP CONSTRAINT "FK_689db3835e5550e68d26ca32676"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_151b79a83ba240b0cb31b2302d1"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_cdb99c05982d5191ac8465ac010"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_f1d359a55923bb45b057fbdab0d"`);
        await queryRunner.query(`ALTER TABLE "shipping_addresses" DROP CONSTRAINT "FK_6f522735551c716dc489635b5b7"`);
        await queryRunner.query(`ALTER TABLE "sellers" DROP CONSTRAINT "FK_4c1c59db4ac1ed90a1a7c0ff3df"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_220faed55dfcb27da93f7ac5421"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_e40a1dd2909378f0da1f34f7bd6"`);
        await queryRunner.query(`ALTER TABLE "attributes" DROP CONSTRAINT "FK_2161c27ae1c917301af344493e7"`);
        await queryRunner.query(`ALTER TABLE "attribute_values" DROP CONSTRAINT "FK_b8f8e1d9141248b538c9285574e"`);
        await queryRunner.query(`ALTER TABLE "attribute_values" DROP CONSTRAINT "FK_c81deba612aa9847bae5be6d64c"`);
        await queryRunner.query(`ALTER TABLE "categories" DROP CONSTRAINT "FK_2c1f40c7ab98d13a79214436d81"`);
        await queryRunner.query(`ALTER TABLE "categories" DROP CONSTRAINT "FK_69d45adbc59b8f44730cc411ca1"`);
        await queryRunner.query(`ALTER TABLE "categories" DROP CONSTRAINT "FK_9a6f051e66982b5f0318981bcaa"`);
        await queryRunner.query(`ALTER TABLE "addresses" DROP CONSTRAINT "FK_95c93a584de49f0b0e13f753630"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e1d833224b5be535323207473f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_40e7da0284a5389344605de8da"`);
        await queryRunner.query(`DROP TABLE "products_categories_categories"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6a7082c3fa6b04083df2a0107b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4df1b7c7386e71711941ac06b4"`);
        await queryRunner.query(`DROP TABLE "products_photos_media_files"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_86033897c009fcca8b6505d6be"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_472b25323af01488f1f66a06b6"`);
        await queryRunner.query(`DROP TABLE "user_roles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b4f3a5b54478bd9a66cb6ad8e4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b4599f8b8f548d35850afa2d12"`);
        await queryRunner.query(`DROP TABLE "role_permissions"`);
        await queryRunner.query(`DROP TABLE "carts"`);
        await queryRunner.query(`DROP TABLE "coupons"`);
        await queryRunner.query(`DROP TYPE "public"."coupon_type_enum"`);
        await queryRunner.query(`DROP TABLE "order_status_history"`);
        await queryRunner.query(`DROP TYPE "public"."order_status_enum"`);
        await queryRunner.query(`DROP TABLE "orders"`);
        await queryRunner.query(`DROP TYPE "public"."payment_method_enum"`);
        await queryRunner.query(`DROP TYPE "public"."payment_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."order_status_enum"`);
        await queryRunner.query(`DROP TABLE "order_items"`);
        await queryRunner.query(`DROP TABLE "shipping_addresses"`);
        await queryRunner.query(`DROP TABLE "sellers"`);
        await queryRunner.query(`DROP TYPE "public"."sellers_verificationstatus_enum"`);
        await queryRunner.query(`DROP TYPE "public"."sellers_status_enum"`);
        await queryRunner.query(`DROP TABLE "products"`);
        await queryRunner.query(`DROP TABLE "attributes"`);
        await queryRunner.query(`DROP TABLE "attribute_values"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9a6f051e66982b5f0318981bca"`);
        await queryRunner.query(`DROP TABLE "categories"`);
        await queryRunner.query(`DROP TABLE "media_files"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TABLE "addresses"`);
        await queryRunner.query(`DROP TYPE "public"."addresses_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."addresses_type_enum"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP TABLE "permissions"`);
    }

}
