import { BaseSeeder } from '../../common/seeders/base.seeder';
import { Country } from './country.entity';

export class CountrySeeder extends BaseSeeder {
  async run(): Promise<void> {
    const countriesData = [
      { id: 1, code: 'AF', name: 'Afghanistan', status: 0 },
      { id: 2, code: 'AL', name: 'Albania', status: 0 },
      { id: 3, code: 'DZ', name: 'Algeria', status: 0 },
      { id: 4, code: 'AS', name: 'American Samoa', status: 0 },
      { id: 5, code: 'AD', name: 'Andorra', status: 0 },
      { id: 6, code: 'AO', name: 'Angola', status: 0 },
      { id: 7, code: 'AI', name: 'Anguilla', status: 0 },
      { id: 8, code: 'AQ', name: 'Antarctica', status: 0 },
      { id: 9, code: 'AG', name: 'Antigua And Barbuda', status: 0 },
      { id: 10, code: 'AR', name: 'Argentina', status: 0 },
      { id: 11, code: 'AM', name: 'Armenia', status: 0 },
      { id: 12, code: 'AW', name: 'Aruba', status: 0 },
      { id: 13, code: 'AU', name: 'Australia', status: 0 },
      { id: 14, code: 'AT', name: 'Austria', status: 0 },
      { id: 15, code: 'AZ', name: 'Azerbaijan', status: 0 },
      { id: 16, code: 'BS', name: 'Bahamas The', status: 0 },
      { id: 17, code: 'BH', name: 'Bahrain', status: 0 },
      { id: 18, code: 'BD', name: 'Bangladesh', status: 0 },
      { id: 19, code: 'BB', name: 'Barbados', status: 0 },
      { id: 20, code: 'BY', name: 'Belarus', status: 0 },
      { id: 21, code: 'BE', name: 'Belgium', status: 0 },
      { id: 22, code: 'BZ', name: 'Belize', status: 0 },
      { id: 23, code: 'BJ', name: 'Benin', status: 0 },
      { id: 24, code: 'BM', name: 'Bermuda', status: 0 },
      { id: 25, code: 'BT', name: 'Bhutan', status: 0 },
      { id: 26, code: 'BO', name: 'Bolivia', status: 0 },
      { id: 27, code: 'BA', name: 'Bosnia and Herzegovina', status: 0 },
      { id: 28, code: 'BW', name: 'Botswana', status: 0 },
      { id: 29, code: 'BV', name: 'Bouvet Island', status: 0 },
      { id: 30, code: 'BR', name: 'Brazil', status: 0 },
      { id: 31, code: 'IO', name: 'British Indian Ocean Territory', status: 0 },
      { id: 32, code: 'BN', name: 'Brunei', status: 0 },
      { id: 33, code: 'BG', name: 'Bulgaria', status: 0 },
      { id: 34, code: 'BF', name: 'Burkina Faso', status: 0 },
      { id: 35, code: 'BI', name: 'Burundi', status: 0 },
      { id: 36, code: 'KH', name: 'Cambodia', status: 0 },
      { id: 37, code: 'CM', name: 'Cameroon', status: 0 },
      { id: 38, code: 'CA', name: 'Canada', status: 0 },
      { id: 39, code: 'CV', name: 'Cape Verde', status: 0 },
      { id: 40, code: 'KY', name: 'Cayman Islands', status: 0 },
      { id: 41, code: 'CF', name: 'Central African Republic', status: 0 },
      { id: 42, code: 'TD', name: 'Chad', status: 0 },
      { id: 43, code: 'CL', name: 'Chile', status: 0 },
      { id: 44, code: 'CN', name: 'China', status: 0 },
      { id: 45, code: 'CX', name: 'Christmas Island', status: 0 },
      { id: 46, code: 'CC', name: 'Cocos (Keeling) Islands', status: 0 },
      { id: 47, code: 'CO', name: 'Colombia', status: 0 },
      { id: 48, code: 'KM', name: 'Comoros', status: 0 },
      { id: 49, code: 'CG', name: 'Republic Of The Congo', status: 0 },
      { id: 50, code: 'CD', name: 'Democratic Republic Of The Congo', status: 0 },
      { id: 51, code: 'CK', name: 'Cook Islands', status: 0 },
      { id: 52, code: 'CR', name: 'Costa Rica', status: 0 },
      { id: 53, code: 'CI', name: 'Cote D\'Ivoire (Ivory Coast)', status: 0 },
      { id: 54, code: 'HR', name: 'Croatia (Hrvatska)', status: 0 },
      { id: 55, code: 'CU', name: 'Cuba', status: 0 },
      { id: 56, code: 'CY', name: 'Cyprus', status: 0 },
      { id: 57, code: 'CZ', name: 'Czech Republic', status: 0 },
      { id: 58, code: 'DK', name: 'Denmark', status: 0 },
      { id: 59, code: 'DJ', name: 'Djibouti', status: 0 },
      { id: 60, code: 'DM', name: 'Dominica', status: 0 },
      { id: 61, code: 'DO', name: 'Dominican Republic', status: 0 },
      { id: 62, code: 'TP', name: 'East Timor', status: 0 },
      { id: 63, code: 'EC', name: 'Ecuador', status: 0 },
      { id: 64, code: 'EG', name: 'Egypt', status: 0 },
      { id: 65, code: 'SV', name: 'El Salvador', status: 0 },
      { id: 66, code: 'GQ', name: 'Equatorial Guinea', status: 0 },
      { id: 67, code: 'ER', name: 'Eritrea', status: 0 },
      { id: 68, code: 'EE', name: 'Estonia', status: 0 },
      { id: 69, code: 'ET', name: 'Ethiopia', status: 0 },
      { id: 70, code: 'XA', name: 'External Territories of Australia', status: 0 },
      { id: 71, code: 'FK', name: 'Falkland Islands', status: 0 },
      { id: 72, code: 'FO', name: 'Faroe Islands', status: 0 },
      { id: 73, code: 'FJ', name: 'Fiji Islands', status: 0 },
      { id: 74, code: 'FI', name: 'Finland', status: 0 },
      { id: 75, code: 'FR', name: 'France', status: 0 },
      { id: 76, code: 'GF', name: 'French Guiana', status: 0 },
      { id: 77, code: 'PF', name: 'French Polynesia', status: 0 },
      { id: 78, code: 'TF', name: 'French Southern Territories', status: 0 },
      { id: 79, code: 'GA', name: 'Gabon', status: 0 },
      { id: 80, code: 'GM', name: 'Gambia The', status: 0 },
      { id: 81, code: 'GE', name: 'Georgia', status: 0 },
      { id: 82, code: 'DE', name: 'Germany', status: 0 },
      { id: 83, code: 'GH', name: 'Ghana', status: 0 },
      { id: 84, code: 'GI', name: 'Gibraltar', status: 0 },
      { id: 85, code: 'GR', name: 'Greece', status: 0 },
      { id: 86, code: 'GL', name: 'Greenland', status: 0 },
      { id: 87, code: 'GD', name: 'Grenada', status: 0 },
      { id: 88, code: 'GP', name: 'Guadeloupe', status: 0 },
      { id: 89, code: 'GU', name: 'Guam', status: 0 },
      { id: 90, code: 'GT', name: 'Guatemala', status: 0 },
      { id: 91, code: 'XU', name: 'Guernsey and Alderney', status: 0 },
      { id: 92, code: 'GN', name: 'Guinea', status: 0 },
      { id: 93, code: 'GW', name: 'Guinea-Bissau', status: 0 },
      { id: 94, code: 'GY', name: 'Guyana', status: 0 },
      { id: 95, code: 'HT', name: 'Haiti', status: 0 },
      { id: 96, code: 'HM', name: 'Heard and McDonald Islands', status: 0 },
      { id: 97, code: 'HN', name: 'Honduras', status: 0 },
      { id: 98, code: 'HK', name: 'Hong Kong S.A.R.', status: 0 },
      { id: 99, code: 'HU', name: 'Hungary', status: 0 },
      { id: 100, code: 'IS', name: 'Iceland', status: 0 },
      { id: 101, code: 'IN', name: 'India', status: 0 },
      { id: 102, code: 'ID', name: 'Indonesia', status: 0 },
      { id: 103, code: 'IR', name: 'Iran', status: 0 },
      { id: 104, code: 'IQ', name: 'Iraq', status: 0 },
      { id: 105, code: 'IE', name: 'Ireland', status: 0 },
      { id: 106, code: 'IL', name: 'Israel', status: 0 },
      { id: 107, code: 'IT', name: 'Italy', status: 0 },
      { id: 108, code: 'JM', name: 'Jamaica', status: 0 },
      { id: 109, code: 'JP', name: 'Japan', status: 0 },
      { id: 110, code: 'XJ', name: 'Jersey', status: 0 },
      { id: 111, code: 'JO', name: 'Jordan', status: 0 },
      { id: 112, code: 'KZ', name: 'Kazakhstan', status: 0 },
      { id: 113, code: 'KE', name: 'Kenya', status: 0 },
      { id: 114, code: 'KI', name: 'Kiribati', status: 0 },
      { id: 115, code: 'KP', name: 'Korea North', status: 0 },
      { id: 116, code: 'KR', name: 'Korea South', status: 0 },
      { id: 117, code: 'KW', name: 'Kuwait', status: 0 },
      { id: 118, code: 'KG', name: 'Kyrgyzstan', status: 0 },
      { id: 119, code: 'LA', name: 'Laos', status: 0 },
      { id: 120, code: 'LV', name: 'Latvia', status: 0 },
      { id: 121, code: 'LB', name: 'Lebanon', status: 0 },
      { id: 122, code: 'LS', name: 'Lesotho', status: 0 },
      { id: 123, code: 'LR', name: 'Liberia', status: 0 },
      { id: 124, code: 'LY', name: 'Libya', status: 0 },
      { id: 125, code: 'LI', name: 'Liechtenstein', status: 0 },
      { id: 126, code: 'LT', name: 'Lithuania', status: 0 },
      { id: 127, code: 'LU', name: 'Luxembourg', status: 0 },
      { id: 128, code: 'MO', name: 'Macau S.A.R.', status: 0 },
      { id: 129, code: 'MK', name: 'Macedonia', status: 0 },
      { id: 130, code: 'MG', name: 'Madagascar', status: 0 },
      { id: 131, code: 'MW', name: 'Malawi', status: 0 },
      { id: 132, code: 'MY', name: 'Malaysia', status: 0 },
      { id: 133, code: 'MV', name: 'Maldives', status: 0 },
      { id: 134, code: 'ML', name: 'Mali', status: 0 },
      { id: 135, code: 'MT', name: 'Malta', status: 0 },
      { id: 136, code: 'XM', name: 'Man (Isle of)', status: 0 },
      { id: 137, code: 'MH', name: 'Marshall Islands', status: 0 },
      { id: 138, code: 'MQ', name: 'Martinique', status: 0 },
      { id: 139, code: 'MR', name: 'Mauritania', status: 0 },
      { id: 140, code: 'MU', name: 'Mauritius', status: 0 },
      { id: 141, code: 'YT', name: 'Mayotte', status: 0 },
      { id: 142, code: 'MX', name: 'Mexico', status: 0 },
      { id: 143, code: 'FM', name: 'Micronesia', status: 0 },
      { id: 144, code: 'MD', name: 'Moldova', status: 0 },
      { id: 145, code: 'MC', name: 'Monaco', status: 0 },
      { id: 146, code: 'MN', name: 'Mongolia', status: 0 },
      { id: 147, code: 'MS', name: 'Montserrat', status: 0 },
      { id: 148, code: 'MA', name: 'Morocco', status: 0 },
      { id: 149, code: 'MZ', name: 'Mozambique', status: 0 },
      { id: 150, code: 'MM', name: 'Myanmar', status: 0 },
      { id: 151, code: 'NA', name: 'Namibia', status: 0 },
      { id: 152, code: 'NR', name: 'Nauru', status: 0 },
      { id: 153, code: 'NP', name: 'Nepal', status: 0 },
      { id: 154, code: 'AN', name: 'Netherlands Antilles', status: 0 },
      { id: 155, code: 'NL', name: 'Netherlands The', status: 0 },
      { id: 156, code: 'NC', name: 'New Caledonia', status: 0 },
      { id: 157, code: 'NZ', name: 'New Zealand', status: 0 },
      { id: 158, code: 'NI', name: 'Nicaragua', status: 0 },
      { id: 159, code: 'NE', name: 'Niger', status: 0 },
      { id: 160, code: 'NG', name: 'Nigeria', status: 0 },
      { id: 161, code: 'NU', name: 'Niue', status: 0 },
      { id: 162, code: 'NF', name: 'Norfolk Island', status: 0 },
      { id: 163, code: 'MP', name: 'Northern Mariana Islands', status: 0 },
      { id: 164, code: 'NO', name: 'Norway', status: 0 },
      { id: 165, code: 'OM', name: 'Oman', status: 0 },
      { id: 166, code: 'PK', name: 'Pakistan', status: 1 },
      { id: 167, code: 'PW', name: 'Palau', status: 0 },
      { id: 168, code: 'PS', name: 'Palestinian Territory Occupied', status: 0 },
      { id: 169, code: 'PA', name: 'Panama', status: 0 },
      { id: 170, code: 'PG', name: 'Papua new Guinea', status: 0 },
      { id: 171, code: 'PY', name: 'Paraguay', status: 0 },
      { id: 172, code: 'PE', name: 'Peru', status: 0 },
      { id: 173, code: 'PH', name: 'Philippines', status: 0 },
      { id: 174, code: 'PN', name: 'Pitcairn Island', status: 0 },
      { id: 175, code: 'PL', name: 'Poland', status: 0 },
      { id: 176, code: 'PT', name: 'Portugal', status: 0 },
      { id: 177, code: 'PR', name: 'Puerto Rico', status: 0 },
      { id: 178, code: 'QA', name: 'Qatar', status: 0 },
      { id: 179, code: 'RE', name: 'Reunion', status: 0 },
      { id: 180, code: 'RO', name: 'Romania', status: 0 },
      { id: 181, code: 'RU', name: 'Russia', status: 0 },
      { id: 182, code: 'RW', name: 'Rwanda', status: 0 },
      { id: 183, code: 'SH', name: 'Saint Helena', status: 0 },
      { id: 184, code: 'KN', name: 'Saint Kitts And Nevis', status: 0 },
      { id: 185, code: 'LC', name: 'Saint Lucia', status: 0 },
      { id: 186, code: 'PM', name: 'Saint Pierre and Miquelon', status: 0 },
      { id: 187, code: 'VC', name: 'Saint Vincent And The Grenadines', status: 0 },
      { id: 188, code: 'WS', name: 'Samoa', status: 0 },
      { id: 189, code: 'SM', name: 'San Marino', status: 0 },
      { id: 190, code: 'ST', name: 'Sao Tome and Principe', status: 0 },
      { id: 191, code: 'SA', name: 'Saudi Arabia', status: 0 },
      { id: 192, code: 'SN', name: 'Senegal', status: 0 },
      { id: 193, code: 'RS', name: 'Serbia', status: 0 },
      { id: 194, code: 'SC', name: 'Seychelles', status: 0 },
      { id: 195, code: 'SL', name: 'Sierra Leone', status: 0 },
      { id: 196, code: 'SG', name: 'Singapore', status: 0 },
      { id: 197, code: 'SK', name: 'Slovakia', status: 0 },
      { id: 198, code: 'SI', name: 'Slovenia', status: 0 },
      { id: 199, code: 'XG', name: 'Smaller Territories of the UK', status: 0 },
      { id: 200, code: 'SB', name: 'Solomon Islands', status: 0 },
      { id: 201, code: 'SO', name: 'Somalia', status: 0 },
      { id: 202, code: 'ZA', name: 'South Africa', status: 0 },
      { id: 203, code: 'GS', name: 'South Georgia', status: 0 },
      { id: 204, code: 'SS', name: 'South Sudan', status: 0 },
      { id: 205, code: 'ES', name: 'Spain', status: 0 },
      { id: 206, code: 'LK', name: 'Sri Lanka', status: 0 },
      { id: 207, code: 'SD', name: 'Sudan', status: 0 },
      { id: 208, code: 'SR', name: 'Suriname', status: 0 },
      { id: 209, code: 'SJ', name: 'Svalbard And Jan Mayen Islands', status: 0 },
      { id: 210, code: 'SZ', name: 'Swaziland', status: 0 },
      { id: 211, code: 'SE', name: 'Sweden', status: 0 },
      { id: 212, code: 'CH', name: 'Switzerland', status: 0 },
      { id: 213, code: 'SY', name: 'Syria', status: 0 },
      { id: 214, code: 'TW', name: 'Taiwan', status: 0 },
      { id: 215, code: 'TJ', name: 'Tajikistan', status: 0 },
      { id: 216, code: 'TZ', name: 'Tanzania', status: 0 },
      { id: 217, code: 'TH', name: 'Thailand', status: 0 },
      { id: 218, code: 'TG', name: 'Togo', status: 0 },
      { id: 219, code: 'TK', name: 'Tokelau', status: 0 },
      { id: 220, code: 'TO', name: 'Tonga', status: 0 },
      { id: 221, code: 'TT', name: 'Trinidad And Tobago', status: 0 },
      { id: 222, code: 'TN', name: 'Tunisia', status: 0 },
      { id: 223, code: 'TR', name: 'Turkey', status: 0 },
      { id: 224, code: 'TM', name: 'Turkmenistan', status: 0 },
      { id: 225, code: 'TC', name: 'Turks And Caicos Islands', status: 0 },
      { id: 226, code: 'TV', name: 'Tuvalu', status: 0 },
      { id: 227, code: 'UG', name: 'Uganda', status: 0 },
      { id: 228, code: 'UA', name: 'Ukraine', status: 0 },
      { id: 229, code: 'AE', name: 'United Arab Emirates', status: 0 },
      { id: 230, code: 'GB', name: 'United Kingdom', status: 0 },
      { id: 231, code: 'US', name: 'United States', status: 0 },
      { id: 232, code: 'UM', name: 'United States Minor Outlying Islands', status: 0 },
      { id: 233, code: 'UY', name: 'Uruguay', status: 0 },
      { id: 234, code: 'UZ', name: 'Uzbekistan', status: 0 },
      { id: 235, code: 'VU', name: 'Vanuatu', status: 0 },
      { id: 236, code: 'VA', name: 'Vatican City State (Holy See)', status: 0 },
      { id: 237, code: 'VE', name: 'Venezuela', status: 0 },
      { id: 238, code: 'VN', name: 'Vietnam', status: 0 },
      { id: 239, code: 'VG', name: 'Virgin Islands (British)', status: 0 },
      { id: 240, code: 'VI', name: 'Virgin Islands (US)', status: 0 },
      { id: 241, code: 'WF', name: 'Wallis And Futuna Islands', status: 0 },
      { id: 242, code: 'EH', name: 'Western Sahara', status: 0 },
      { id: 243, code: 'YE', name: 'Yemen', status: 0 },
      { id: 244, code: 'YU', name: 'Yugoslavia', status: 0 },
      { id: 245, code: 'ZM', name: 'Zambia', status: 0 },
      { id: 246, code: 'ZW', name: 'Zimbabwe', status: 0 }
    ];

    console.log('Seeding countries...');
    
    // Clear existing data
    await this.dataSource.query('TRUNCATE TABLE countries');
    
    // Insert all countries
    await this.saveMany(countriesData, Country);
    
    console.log(`Seeded ${countriesData.length} countries successfully`);
  }
} 