import { BaseSeeder } from '../../common/seeders/base.seeder';
import { Country } from './country.entity';

export class CountrySeeder extends BaseSeeder {
  async run(): Promise<void> {
    const countriesData = [
      { code: 'AF', name: 'Afghanistan', isActive: false },
      { code: 'AL', name: 'Albania', isActive: false },
      { code: 'DZ', name: 'Algeria', isActive: false },
      { code: 'AS', name: 'American Samoa', isActive: false },
      { code: 'AD', name: 'Andorra', isActive: false },
      { code: 'AO', name: 'Angola', isActive: false },
      { code: 'AI', name: 'Anguilla', isActive: false },
      { code: 'AQ', name: 'Antarctica', isActive: false },
      { code: 'AG', name: 'Antigua And Barbuda', isActive: false },
      { code: 'AR', name: 'Argentina', isActive: false },
      { code: 'AM', name: 'Armenia', isActive: false },
      { code: 'AW', name: 'Aruba', isActive: false },
      { code: 'AU', name: 'Australia', isActive: false },
      { code: 'AT', name: 'Austria', isActive: false },
      { code: 'AZ', name: 'Azerbaijan', isActive: false },
      { code: 'BS', name: 'Bahamas The', isActive: false },
      { code: 'BH', name: 'Bahrain', isActive: false },
      { code: 'BD', name: 'Bangladesh', isActive: false },
      { code: 'BB', name: 'Barbados', isActive: false },
      { code: 'BY', name: 'Belarus', isActive: false },
      { code: 'BE', name: 'Belgium', isActive: false },
      { code: 'BZ', name: 'Belize', isActive: false },
      { code: 'BJ', name: 'Benin', isActive: false },
      { code: 'BM', name: 'Bermuda', isActive: false },
      { code: 'BT', name: 'Bhutan', isActive: false },
      { code: 'BO', name: 'Bolivia', isActive: false },
      { code: 'BA', name: 'Bosnia and Herzegovina', isActive: false },
      { code: 'BW', name: 'Botswana', isActive: false },
      { code: 'BV', name: 'Bouvet Island', isActive: false },
      { code: 'BR', name: 'Brazil', isActive: false },
      { code: 'IO', name: 'British Indian Ocean Territory', isActive: false },
      { code: 'BN', name: 'Brunei', isActive: false },
      { code: 'BG', name: 'Bulgaria', isActive: false },
      { code: 'BF', name: 'Burkina Faso', isActive: false },
      { code: 'BI', name: 'Burundi', isActive: false },
      { code: 'KH', name: 'Cambodia', isActive: false },
      { code: 'CM', name: 'Cameroon', isActive: false },
      { code: 'CA', name: 'Canada', isActive: false },
      { code: 'CV', name: 'Cape Verde', isActive: false },
      { code: 'KY', name: 'Cayman Islands', isActive: false },
      { code: 'CF', name: 'Central African Republic', isActive: false },
      { code: 'TD', name: 'Chad', isActive: false },
      { code: 'CL', name: 'Chile', isActive: false },
      { code: 'CN', name: 'China', isActive: false },
      { code: 'CX', name: 'Christmas Island', isActive: false },
      { code: 'CC', name: 'Cocos (Keeling) Islands', isActive: false },
      { code: 'CO', name: 'Colombia', isActive: false },
      { code: 'KM', name: 'Comoros', isActive: false },
      { code: 'CG', name: 'Republic Of The Congo', isActive: false },
      { code: 'CD', name: 'Democratic Republic Of The Congo', isActive: false },
      { code: 'CK', name: 'Cook Islands', isActive: false },
      { code: 'CR', name: 'Costa Rica', isActive: false },
      { code: 'CI', name: 'Cote D\'Ivoire (Ivory Coast)', isActive: false },
      { code: 'HR', name: 'Croatia (Hrvatska)', isActive: false },
      { code: 'CU', name: 'Cuba', isActive: false },
      { code: 'CY', name: 'Cyprus', isActive: false },
      { code: 'CZ', name: 'Czech Republic', isActive: false },
      { code: 'DK', name: 'Denmark', isActive: false },
      { code: 'DJ', name: 'Djibouti', isActive: false },
      { code: 'DM', name: 'Dominica', isActive: false },
      { code: 'DO', name: 'Dominican Republic', isActive: false },
      { code: 'TP', name: 'East Timor', isActive: false },
      { code: 'EC', name: 'Ecuador', isActive: false },
      { code: 'EG', name: 'Egypt', isActive: false },
      { code: 'SV', name: 'El Salvador', isActive: false },
      { code: 'GQ', name: 'Equatorial Guinea', isActive: false },
      { code: 'ER', name: 'Eritrea', isActive: false },
      { code: 'EE', name: 'Estonia', isActive: false },
      { code: 'ET', name: 'Ethiopia', isActive: false },
      { code: 'XA', name: 'External Territories of Australia', isActive: false },
      { code: 'FK', name: 'Falkland Islands', isActive: false },
      { code: 'FO', name: 'Faroe Islands', isActive: false },
      { code: 'FJ', name: 'Fiji Islands', isActive: false },
      { code: 'FI', name: 'Finland', isActive: false },
      { code: 'FR', name: 'France', isActive: false },
      { code: 'GF', name: 'French Guiana', isActive: false },
      { code: 'PF', name: 'French Polynesia', isActive: false },
      { code: 'TF', name: 'French Southern Territories', isActive: false },
      { code: 'GA', name: 'Gabon', isActive: false },
      { code: 'GM', name: 'Gambia The', isActive: false },
      { code: 'GE', name: 'Georgia', isActive: false },
      { code: 'DE', name: 'Germany', isActive: false },
      { code: 'GH', name: 'Ghana', isActive: false },
      { code: 'GI', name: 'Gibraltar', isActive: false },
      { code: 'GR', name: 'Greece', isActive: false },
      { code: 'GL', name: 'Greenland', isActive: false },
      { code: 'GD', name: 'Grenada', isActive: false },
      { code: 'GP', name: 'Guadeloupe', isActive: false },
      { code: 'GU', name: 'Guam', isActive: false },
      { code: 'GT', name: 'Guatemala', isActive: false },
      { code: 'XU', name: 'Guernsey and Alderney', isActive: false },
      { code: 'GN', name: 'Guinea', isActive: false },
      { code: 'GW', name: 'Guinea-Bissau', isActive: false },
      { code: 'GY', name: 'Guyana', isActive: false },
      { code: 'HT', name: 'Haiti', isActive: false },
      { code: 'HM', name: 'Heard and McDonald Islands', isActive: false },
      { code: 'HN', name: 'Honduras', isActive: false },
      { code: 'HK', name: 'Hong Kong S.A.R.', isActive: false },
      { code: 'HU', name: 'Hungary', isActive: false },
      { code: 'IS', name: 'Iceland', isActive: false },
      { code: 'IN', name: 'India', isActive: false },
      { code: 'ID', name: 'Indonesia', isActive: false },
      { code: 'IR', name: 'Iran', isActive: false },
      { code: 'IQ', name: 'Iraq', isActive: false },
      { code: 'IE', name: 'Ireland', isActive: false },
      { code: 'IL', name: 'Israel', isActive: false },
      { code: 'IT', name: 'Italy', isActive: false },
      { code: 'JM', name: 'Jamaica', isActive: false },
      { code: 'JP', name: 'Japan', isActive: false },
      { code: 'XJ', name: 'Jersey', isActive: false },
      { code: 'JO', name: 'Jordan', isActive: false },
      { code: 'KZ', name: 'Kazakhstan', isActive: false },
      { code: 'KE', name: 'Kenya', isActive: false },
      { code: 'KI', name: 'Kiribati', isActive: false },
      { code: 'KP', name: 'Korea North', isActive: false },
      { code: 'KR', name: 'Korea South', isActive: false },
      { code: 'KW', name: 'Kuwait', isActive: false },
      { code: 'KG', name: 'Kyrgyzstan', isActive: false },
      { code: 'LA', name: 'Laos', isActive: false },
      { code: 'LV', name: 'Latvia', isActive: false },
      { code: 'LB', name: 'Lebanon', isActive: false },
      { code: 'LS', name: 'Lesotho', isActive: false },
      { code: 'LR', name: 'Liberia', isActive: false },
      { code: 'LY', name: 'Libya', isActive: false },
      { code: 'LI', name: 'Liechtenstein', isActive: false },
      { code: 'LT', name: 'Lithuania', isActive: false },
      { code: 'LU', name: 'Luxembourg', isActive: false },
      { code: 'MO', name: 'Macau S.A.R.', isActive: false },
      { code: 'MK', name: 'Macedonia', isActive: false },
      { code: 'MG', name: 'Madagascar', isActive: false },
      { code: 'MW', name: 'Malawi', isActive: false },
      { code: 'MY', name: 'Malaysia', isActive: false },
      { code: 'MV', name: 'Maldives', isActive: false },
      { code: 'ML', name: 'Mali', isActive: false },
      { code: 'MT', name: 'Malta', isActive: false },
      { code: 'XM', name: 'Man (Isle of)', isActive: false },
      { code: 'MH', name: 'Marshall Islands', isActive: false },
      { code: 'MQ', name: 'Martinique', isActive: false },
      { code: 'MR', name: 'Mauritania', isActive: false },
      { code: 'MU', name: 'Mauritius', isActive: false },
      { code: 'YT', name: 'Mayotte', isActive: false },
      { code: 'MX', name: 'Mexico', isActive: false },
      { code: 'FM', name: 'Micronesia', isActive: false },
      { code: 'MD', name: 'Moldova', isActive: false },
      { code: 'MC', name: 'Monaco', isActive: false },
      { code: 'MN', name: 'Mongolia', isActive: false },
      { code: 'MS', name: 'Montserrat', isActive: false },
      { code: 'MA', name: 'Morocco', isActive: false },
      { code: 'MZ', name: 'Mozambique', isActive: false },
      { code: 'MM', name: 'Myanmar', isActive: false },
      { code: 'NA', name: 'Namibia', isActive: false },
      { code: 'NR', name: 'Nauru', isActive: false },
      { code: 'NP', name: 'Nepal', isActive: false },
      { code: 'AN', name: 'Netherlands Antilles', isActive: false },
      { code: 'NL', name: 'Netherlands The', isActive: false },
      { code: 'NC', name: 'New Caledonia', isActive: false },
      { code: 'NZ', name: 'New Zealand', isActive: false },
      { code: 'NI', name: 'Nicaragua', isActive: false },
      { code: 'NE', name: 'Niger', isActive: false },
      { code: 'NG', name: 'Nigeria', isActive: false },
      { code: 'NU', name: 'Niue', isActive: false },
      { code: 'NF', name: 'Norfolk Island', isActive: false },
      { code: 'MP', name: 'Northern Mariana Islands', isActive: false },
      { code: 'NO', name: 'Norway', isActive: false },
      { code: 'OM', name: 'Oman', isActive: false },
      { code: 'PK', name: 'Pakistan', isActive: true },
      { code: 'PW', name: 'Palau', isActive: false },
      { code: 'PS', name: 'Palestinian Territory Occupied', isActive: false },
      { code: 'PA', name: 'Panama', isActive: false },
      { code: 'PG', name: 'Papua new Guinea', isActive: false },
      { code: 'PY', name: 'Paraguay', isActive: false },
      { code: 'PE', name: 'Peru', isActive: false },
      { code: 'PH', name: 'Philippines', isActive: false },
      { code: 'PN', name: 'Pitcairn Island', isActive: false },
      { code: 'PL', name: 'Poland', isActive: false },
      { code: 'PT', name: 'Portugal', isActive: false },
      { code: 'PR', name: 'Puerto Rico', isActive: false },
      { code: 'QA', name: 'Qatar', isActive: false },
      { code: 'RE', name: 'Reunion', isActive: false },
      { code: 'RO', name: 'Romania', isActive: false },
      { code: 'RU', name: 'Russia', isActive: false },
      { code: 'RW', name: 'Rwanda', isActive: false },
      { code: 'SH', name: 'Saint Helena', isActive: false },
      { code: 'KN', name: 'Saint Kitts And Nevis', isActive: false },
      { code: 'LC', name: 'Saint Lucia', isActive: false },
      { code: 'PM', name: 'Saint Pierre and Miquelon', isActive: false },
      { code: 'VC', name: 'Saint Vincent And The Grenadines', isActive: false },
      { code: 'WS', name: 'Samoa', isActive: false },
      { code: 'SM', name: 'San Marino', isActive: false },
      { code: 'ST', name: 'Sao Tome and Principe', isActive: false },
      { code: 'SA', name: 'Saudi Arabia', isActive: false },
      { code: 'SN', name: 'Senegal', isActive: false },
      { code: 'RS', name: 'Serbia', isActive: false },
      { code: 'SC', name: 'Seychelles', isActive: false },
      { code: 'SL', name: 'Sierra Leone', isActive: false },
      { code: 'SG', name: 'Singapore', isActive: false },
      { code: 'SK', name: 'Slovakia', isActive: false },
      { code: 'SI', name: 'Slovenia', isActive: false },
      { code: 'XG', name: 'Smaller Territories of the UK', isActive: false },
      { code: 'SB', name: 'Solomon Islands', isActive: false },
      { code: 'SO', name: 'Somalia', isActive: false },
      { code: 'ZA', name: 'South Africa', isActive: false },
      { code: 'GS', name: 'South Georgia', isActive: false },
      { code: 'SS', name: 'South Sudan', isActive: false },
      { code: 'ES', name: 'Spain', isActive: false },
      { code: 'LK', name: 'Sri Lanka', isActive: false },
      { code: 'SD', name: 'Sudan', isActive: false },
      { code: 'SR', name: 'Suriname', isActive: false },
      { code: 'SJ', name: 'Svalbard And Jan Mayen Islands', isActive: false },
      { code: 'SZ', name: 'Swaziland', isActive: false },
      { code: 'SE', name: 'Sweden', isActive: false },
      { code: 'CH', name: 'Switzerland', isActive: false },
      { code: 'SY', name: 'Syria', isActive: false },
      { code: 'TW', name: 'Taiwan', isActive: false },
      { code: 'TJ', name: 'Tajikistan', isActive: false },
      { code: 'TZ', name: 'Tanzania', isActive: false },
      { code: 'TH', name: 'Thailand', isActive: false },
      { code: 'TG', name: 'Togo', isActive: false },
      { code: 'TK', name: 'Tokelau', isActive: false },
      { code: 'TO', name: 'Tonga', isActive: false },
      { code: 'TT', name: 'Trinidad And Tobago', isActive: false },
      { code: 'TN', name: 'Tunisia', isActive: false },
      { code: 'TR', name: 'Turkey', isActive: false },
      { code: 'TM', name: 'Turkmenistan', isActive: false },
      { code: 'TC', name: 'Turks And Caicos Islands', isActive: false },
      { code: 'TV', name: 'Tuvalu', isActive: false },
      { code: 'UG', name: 'Uganda', isActive: false },
      { code: 'UA', name: 'Ukraine', isActive: false },
      { code: 'AE', name: 'United Arab Emirates', isActive: false },
      { code: 'GB', name: 'United Kingdom', isActive: false },
      { code: 'US', name: 'United States', isActive: false },
      { code: 'UM', name: 'United States Minor Outlying Islands', isActive: false },
      { code: 'UY', name: 'Uruguay', isActive: false },
      { code: 'UZ', name: 'Uzbekistan', isActive: false },
      { code: 'VU', name: 'Vanuatu', isActive: false },
      { code: 'VA', name: 'Vatican City State (Holy See)', isActive: false },
      { code: 'VE', name: 'Venezuela', isActive: false },
      { code: 'VN', name: 'Vietnam', isActive: false },
      { code: 'VG', name: 'Virgin Islands (British)', isActive: false },
      { code: 'VI', name: 'Virgin Islands (US)', isActive: false },
      { code: 'WF', name: 'Wallis And Futuna Islands', isActive: false },
      { code: 'EH', name: 'Western Sahara', isActive: false },
      { code: 'YE', name: 'Yemen', isActive: false },
      { code: 'YU', name: 'Yugoslavia', isActive: false },
      { code: 'ZM', name: 'Zambia', isActive: false },
      { code: 'ZW', name: 'Zimbabwe', isActive: false }
    ];

    console.log('Seeding countries...');
    
    // Clear existing data
    await this.dataSource.query('TRUNCATE TABLE countries');
    
    // Insert all countries
    await this.saveMany(countriesData, Country);
    
    console.log(`Seeded ${countriesData.length} countries successfully`);
  }
} 